
# Setup
title: miklós tusz
tagline: A blog about space, code, and other neat things
url: http://www.miklostusz.com
paginate: 5
baseurl: ""

collections:
  - images

markdown: kramdown
excerpt_separator: <!-- fold -->

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Miklós Tusz
  twitter: https://twitter.com/mdtusz
  github: https://github.com/mdtusz
  stackexchange: http://stackexchange.com/users/4119555/mikl%C3%B3s-tusz
  instagram: https://instagram.com/mdtusz
  email: mdtusz@gmail.com

# Custom vars
version: 1.0.0
github:
  repo:

gems: [jekyll-paginate]
