
# Setup
title: miklós tusz
tagline: A blog about space, code, and other neat things
url: http://www.miklostusz.com
paginate: 5
baseurl: ""

collections:
  - images

markdown: kramdown
excerpt_separator: <!-- fold -->

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# About/contact
author:
  name: Miklós Tusz
  github: https://github.com/mdtusz
  keybase: https://keybase.io/mdtusz
  email: mdtusz@gmail.com

# Custom vars
version: 1.0.0
github:
  repo:

plugins: [jekyll-paginate]
